
spring.application.name=TogetherHousing
server.port=9090

#mysql Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/together_housing?sslMode=VERIFY_IDENTITY
spring.datasource.username=3DMKbJv1Pf2d26c.root
spring.datasource.password=nLJchTw9LzyN6lwj


#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true